### ISSUE TITLE
missing formula symbol in view mode

### ISSUE THREAD

**Issue by hoopyoung** [jersou/markdown-explorer#5]
in edit mode, It shows good:
![852ef1bf-3965-4008-b355-4e188f1f09ee](https://user-images.githubusercontent.com/16290557/39991815-517f915e-57a3-11e8-9b5a-6dddb6d4e6a6.jpg)

in view mode,formula miss ... symbol
![1e5c0eae-e209-4788-bedf-fa7aec1b49ca](https://user-images.githubusercontent.com/16290557/39991763-210e9c36-57a3-11e8-96ee-22aa83a28a18.jpg)

my formula image url input : https://latex.codecogs.com/svg.latex?\Large&space;SMA=\frac{p_1+p_2+...+p_n}{n}

is it a bug while parsing the img url with dot in view mode? 

I simply change 3 dot to 2 dot，It works good in view mode now. could anyone tell me why

**Comment by jersou** [comment]
Thank for the report, unfortunately, it's a bug in ShowdownJs (the library used by Markdown-Explorer to render the md files).

I reproduced the bug here : http://demo.showdownjs.com/
![screenshot25](https://user-images.githubusercontent.com/5874319/45268238-351dfb80-b479-11e8-813d-cf130b194c29.png)

I think Showdownjs replaces all the occurrences of the 3 dot with the single character "3dots" (…) : between A and B above ("A…B...").
